changed require for dojo 1.8.0 compat
I get this error when running the bootstrap with dojo sdk 1.8.0:

^Cda@da-HP-ProBook-6560b:~/Da/prj/dawebsite$ node src/dojos/bootstrap.js 

fs.js:338
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/home/da/Da/prj/dawebsite/src/dojo/_base/Url.js'
    at Object.fs.openSync (fs.js:338:18)
    at Object.fs.readFileSync (fs.js:182:15)
    at Function.exports.config.nodeConfig.loaderPatch.getText (/home/da/Da/prj/dawebsite/src/dojo/_base/configNode.js:80:15)
    at injectModule (/home/da/Da/prj/dawebsite/src/dojo/dojo.js:1483:12)
    at forEach (/home/da/Da/prj/dawebsite/src/dojo/dojo.js:93:6)
    at injectDependencies (/home/da/Da/prj/dawebsite/src/dojo/dojo.js:706:5)
    at guardCheckComplete (/home/da/Da/prj/dawebsite/src/dojo/dojo.js:1225:5)
    at injectDependencies (/home/da/Da/prj/dawebsite/src/dojo/dojo.js:705:4)
    at runDefQ (/home/da/Da/prj/dawebsite/src/dojo/dojo.js:1565:6)
    at forEach (/home/da/Da/prj/dawebsite/src/dojo/dojo.js:93:6)

Server.js requires a non-existing file, so I just changed the require accordingly.
Note: I didn't test the change with previous versions of Dojo, so this mod might not work for Dojo < 1.8.